AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - config/**/*
    - node_modules/**/*
    - tmp/**/*

Rails:
  Enabled: true

Style/DoubleNegation:
  Enabled: false
  
Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/ActionFilter:
  Enabled: false

Rails/Delegate:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:
  Max: 15

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/BracesAroundHashParameters:
  Enabled: false
